services:
  clip-backend:
    image: ${DOCKER_IMAGE}:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - .:/clip-backend
    ports:
      - "8000:8000"
    restart: always
