# Generated by Django 5.1.3 on 2024-11-25 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(16)]),
        ),
    ]
