# Generated by Django 5.1.3 on 2024-11-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meeting_is_paused_alter_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='has_joined',
        ),
    ]
