# Generated by Django 5.1.3 on 2024-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_meetingparticipant_has_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='save_minutes',
            field=models.BooleanField(default=True),
        ),
    ]
