# Generated by Django 5.1.3 on 2024-11-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_active',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('ongoing', 'Ongoing'), ('false', 'False')], default='true', max_length=10),
        ),
    ]
