# Generated by Django 5.1.3 on 2024-11-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_alter_meeting_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='start_time',
        ),
    ]
